//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STSendpoints.sts {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice", ConfigurationName="sts.IWSTrustFeb2005Async")]
    public interface IWSTrustFeb2005Async {
        
        // CODEGEN: Generating message contract since the operation TrustFeb2005IssueAsync is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue", ReplyAction="http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STSendpoints.sts.TrustFeb2005IssueAsyncResponse TrustFeb2005IssueAsync(STSendpoints.sts.TrustFeb2005IssueAsyncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/02/trust")]
    public partial class RequestSecurityTokenType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestSecurityTokenResponseType", Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenResponseType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenResponseCollectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestSecurityTokenResponseType1[] requestSecurityTokenResponseField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestSecurityTokenResponse", Order=0)]
        public RequestSecurityTokenResponseType1[] RequestSecurityTokenResponse {
            get {
                return this.requestSecurityTokenResponseField;
            }
            set {
                this.requestSecurityTokenResponseField = value;
                this.RaisePropertyChanged("RequestSecurityTokenResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestSecurityTokenType", Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/02/trust")]
    public partial class RequestSecurityTokenResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustFeb2005IssueAsyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/02/trust", Order=0)]
        public STSendpoints.sts.RequestSecurityTokenType RequestSecurityToken;
        
        public TrustFeb2005IssueAsyncRequest() {
        }
        
        public TrustFeb2005IssueAsyncRequest(STSendpoints.sts.RequestSecurityTokenType RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustFeb2005IssueAsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/02/trust", Order=0)]
        public STSendpoints.sts.RequestSecurityTokenResponseType RequestSecurityTokenResponse;
        
        public TrustFeb2005IssueAsyncResponse() {
        }
        
        public TrustFeb2005IssueAsyncResponse(STSendpoints.sts.RequestSecurityTokenResponseType RequestSecurityTokenResponse) {
            this.RequestSecurityTokenResponse = RequestSecurityTokenResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTrustFeb2005AsyncChannel : STSendpoints.sts.IWSTrustFeb2005Async, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTrustFeb2005AsyncClient : System.ServiceModel.ClientBase<STSendpoints.sts.IWSTrustFeb2005Async>, STSendpoints.sts.IWSTrustFeb2005Async {
        
        public WSTrustFeb2005AsyncClient() {
        }
        
        public WSTrustFeb2005AsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTrustFeb2005AsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrustFeb2005AsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrustFeb2005AsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STSendpoints.sts.TrustFeb2005IssueAsyncResponse STSendpoints.sts.IWSTrustFeb2005Async.TrustFeb2005IssueAsync(STSendpoints.sts.TrustFeb2005IssueAsyncRequest request) {
            return base.Channel.TrustFeb2005IssueAsync(request);
        }
        
        public STSendpoints.sts.RequestSecurityTokenResponseType TrustFeb2005IssueAsync(STSendpoints.sts.RequestSecurityTokenType RequestSecurityToken) {
            STSendpoints.sts.TrustFeb2005IssueAsyncRequest inValue = new STSendpoints.sts.TrustFeb2005IssueAsyncRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            STSendpoints.sts.TrustFeb2005IssueAsyncResponse retVal = ((STSendpoints.sts.IWSTrustFeb2005Async)(this)).TrustFeb2005IssueAsync(inValue);
            return retVal.RequestSecurityTokenResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice", ConfigurationName="sts.IWSTrust13Async")]
    public interface IWSTrust13Async {
        
        // CODEGEN: Generating message contract since the operation Trust13IssueAsync is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTRC/IssueFinal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        STSendpoints.sts.Trust13IssueAsyncResponse Trust13IssueAsync(STSendpoints.sts.Trust13IssueAsyncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13IssueAsyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public STSendpoints.sts.RequestSecurityTokenType1 RequestSecurityToken;
        
        public Trust13IssueAsyncRequest() {
        }
        
        public Trust13IssueAsyncRequest(STSendpoints.sts.RequestSecurityTokenType1 RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13IssueAsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public STSendpoints.sts.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public Trust13IssueAsyncResponse() {
        }
        
        public Trust13IssueAsyncResponse(STSendpoints.sts.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection) {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTrust13AsyncChannel : STSendpoints.sts.IWSTrust13Async, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTrust13AsyncClient : System.ServiceModel.ClientBase<STSendpoints.sts.IWSTrust13Async>, STSendpoints.sts.IWSTrust13Async {
        
        public WSTrust13AsyncClient() {
        }
        
        public WSTrust13AsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTrust13AsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrust13AsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrust13AsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STSendpoints.sts.Trust13IssueAsyncResponse STSendpoints.sts.IWSTrust13Async.Trust13IssueAsync(STSendpoints.sts.Trust13IssueAsyncRequest request) {
            return base.Channel.Trust13IssueAsync(request);
        }
        
        public STSendpoints.sts.RequestSecurityTokenResponseCollectionType Trust13IssueAsync(STSendpoints.sts.RequestSecurityTokenType1 RequestSecurityToken) {
            STSendpoints.sts.Trust13IssueAsyncRequest inValue = new STSendpoints.sts.Trust13IssueAsyncRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            STSendpoints.sts.Trust13IssueAsyncResponse retVal = ((STSendpoints.sts.IWSTrust13Async)(this)).Trust13IssueAsync(inValue);
            return retVal.RequestSecurityTokenResponseCollection;
        }
    }
}
